apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.clusterName }}
  labels:
    {{- include "capaso.commonLabels" . | nindent 4 }}
spec:
  {{- if .Values.clusterNetwork }}
  clusterNetwork:
    {{- toYaml .Values.clusterNetwork | nindent 4 }}
  {{- end }}
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ASOManagedControlPlane
    name: {{ .Values.clusterName }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ASOManagedCluster
    name: {{ .Values.clusterName }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ASOManagedCluster
metadata:
  name: {{ .Values.clusterName }}
  labels:
    {{- include "capaso.commonLabels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
  - apiVersion: resources.azure.com/v1api20200601
    kind: ResourceGroup
    metadata:
      name: {{ .Values.clusterName }}
      annotations:
        {{- include "capaso.asoResourceAnnotations" . | nindent 8 }}
    spec:
      azureName: {{ .Values.clusterName }}
      location: {{ .Values.location }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ASOManagedControlPlane
metadata:
  name: {{ .Values.clusterName }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  version: {{ .Values.kubernetesVersion }}
  resources:
  - apiVersion: containerservice.azure.com/v1api20231001
    kind: ManagedCluster
    metadata:
      name: {{ .Values.clusterName }}
      annotations:
        {{- include "capaso.asoResourceAnnotations" . | nindent 8 }}
    spec:
      azureName: {{ .Values.clusterName }}
      location: {{ .Values.location }}
      operatorSpec:
        secrets:
          adminCredentials:
            name: {{ .Values.clusterName }}-kubeconfig
            key: value
      agentPoolProfiles:
        - vmSize: standard_d2_v2
          name: pool0
          count: 1
          mode: System
      dnsPrefix: {{ .Values.clusterName }}
      identity:
        type: SystemAssigned
      owner:
        name: {{ .Values.clusterName }}
      servicePrincipalProfile:
        clientId: msi
