apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "capaso.clusterName" .  | quote }}
  labels:
    {{- include "capaso.commonLabels" . | nindent 4 }}
spec:
{{- if .Values.withTopology }}
  topology:
    class: {{ .Values.clusterClassName | quote }}
    version: {{ .Values.kubernetesVersion | quote }}
    workers:
      machinePools:
      {{- range $mpName, $mp := .Values.managedMachinePoolSpecs }}
      - class: {{ quote $mpName }}
        name: {{ quote $mpName }}
        replicas: {{ default 1 $mp.count}}
      {{- end }}
{{- else }}
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ASOManagedControlPlane
    name: {{ include "capaso.clusterName" .  | quote }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ASOManagedCluster
    name: {{ include "capaso.clusterName" .  | quote }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ASOManagedCluster
metadata:
  name: {{ include "capaso.clusterName" .  | quote }}
  labels:
    {{- include "capaso.commonLabels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- include "capaso.asoManagedClusterSpec" (list $ (include "capaso.clusterName" $)) | nindent 2 }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ASOManagedControlPlane
metadata:
  name: {{ include "capaso.clusterName" .  | quote }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- include "capaso.asoManagedControlPlaneSpec" (list $ (include "capaso.clusterName" $)) | nindent 2 }}
{{- range $mpName, $mp := .Values.managedMachinePoolSpecs }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: {{ printf "%s-%s" (include "capaso.clusterName" $) $mpName | quote }}
  labels:
    {{- include "capaso.commonLabels" $ | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  clusterName: {{ include "capaso.clusterName" $ | quote }}
  {{- if (ne nil $mp.count) }}
  replicas: {{ $mp.count }}
  {{- end }}
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: {{ include "capaso.clusterName" $ }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ASOManagedMachinePool
        name: {{ printf "%s-%s" (include "capaso.clusterName" $) $mpName | quote }}
      version: {{ default $.Values.kubernetesVersion $mp.orchestratorVersion | quote }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ASOManagedMachinePool
metadata:
  name: {{ printf "%s-%s" (include "capaso.clusterName" $) $mpName | quote }}
  labels:
    {{- include "capaso.commonLabels" $ | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  {{- include "capaso.asoManagedMachinePoolSpec" (list $ (include "capaso.clusterName" $) $mpName $mp) | nindent 2 }}
{{- end }}
{{- end }}{{/* if .Values.withTopology */}}
