{{- range $mpName, $mp := .Values.managedMachinePoolSpecs }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: {{ printf "%s-%s" (include "capaso.clusterName" $) $mpName | quote }}
  labels:
    {{- include "capaso.commonLabels" $ | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  clusterName: {{ include "capaso.clusterName" $ | quote }}
  {{- if (ne nil $mp.count) }}
  replicas: {{ $mp.count }}
  {{- end }}
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: {{ include "capaso.clusterName" $ }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ASOManagedMachinePool
        name: {{ printf "%s-%s" (include "capaso.clusterName" $) $mpName | quote }}
      version: {{ default $.Values.kubernetesVersion $mp.orchestratorVersion | quote }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ASOManagedMachinePool
metadata:
  name: {{ printf "%s-%s" (include "capaso.clusterName" $) $mpName | quote }}
  labels:
    {{- include "capaso.commonLabels" $ | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
  - apiVersion: "containerservice.azure.com/{{ $.Values.managedMachinePoolAPIVersion }}"
    kind: ManagedClustersAgentPool
    metadata:
      name: {{ printf "%s-%s" (include "capaso.clusterName" $) $mpName | quote }}
      annotations:
        {{- include "capaso.asoResourceAnnotations" $ | nindent 8 }}
    spec:
      azureName: {{ $mpName | quote }}
      {{- if $mp.owner }}
        {{- fail (printf ".Values.managedMachinePoolSpecs.%s.owner is not allowed to be set." $mpName) }}
      {{- end }}
      owner:
        name: {{ include "capaso.clusterName" $  | quote }}
      {{- toYaml $mp | nindent 6}}
---
{{- end }}
