{{- range $mpName, $mp := .Values.machinePools }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: {{ printf "%s-%s" (include "capaso.clusterName" $) $mpName | quote }}
  labels:
    {{- include "capaso.commonLabels" $ | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  clusterName: {{ include "capaso.clusterName" $ | quote }}
  replicas: {{ $mp.replicas }}
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: {{ include "capaso.clusterName" $ }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ASOManagedMachinePool
        name: {{ printf "%s-%s" (include "capaso.clusterName" $) $mpName | quote }}
      version: {{ default $.Values.kubernetesVersion $mp.kubernetesVersion }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ASOManagedMachinePool
metadata:
  name: {{ printf "%s-%s" (include "capaso.clusterName" $) $mpName | quote }}
  labels:
    {{- include "capaso.commonLabels" $ | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  resources:
    - apiVersion: containerservice.azure.com/v1api20231001
      kind: ManagedClustersAgentPool
      metadata:
        name: {{ $mpName | quote }}
      spec:
        owner:
          name: {{ include "capaso.clusterName" $  | quote }}
        count: {{ $mp.replicas }}
        vmSize: Standard_DS2_v2
        mode: {{ $mp.mode | quote }}
---
{{- end }}
