credentialSecretName: "aso-credentials"
subscriptionID: ""
tenantID: ""
clientID: ""
clientSecret: ""

# clusterName defaults to the name of the Helm release
clusterName: ""
location: eastus
clusterNetwork: null
kubernetesVersion: v1.28.3

managedClusterAPIVersion: v1api20231001
managedClusterSpec:
  identity:
    type: SystemAssigned
  servicePrincipalProfile:
    clientId: msi

managedMachinePoolAPIVersion: v1api20231001
managedMachinePoolSpecs:
  pool0:
    count: 1
    mode: System
    vmSize: Standard_DS2_v2
