# This shows how a default overlay can be inherited to include extra configuration.

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../default

patches:
  - path: patches/cluster.yaml
