apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: KubeadmControlPlane
      fieldPath: apiVersion
    targets:
      - select:
          group: cluster.x-k8s.io
          version: v1beta1
          kind: Cluster
          name: ${CLUSTER_NAME}
        fieldPaths:
          - spec.controlPlaneRef.apiVersion
        options:
          create: true
  - source:
      kind: KubeadmControlPlane
      fieldPath: kind
    targets:
      - select:
          group: cluster.x-k8s.io
          version: v1beta1
          kind: Cluster
          name: ${CLUSTER_NAME}
        fieldPaths:
          - spec.controlPlaneRef.kind
        options:
          create: true
  - source:
      kind: KubeadmControlPlane
      fieldPath: metadata.name
    targets:
      - select:
          group: cluster.x-k8s.io
          version: v1beta1
          kind: Cluster
          name: ${CLUSTER_NAME}
        fieldPaths:
          - spec.controlPlaneRef.name
        options:
          create: true
