apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../base
- azure-managed-control-plane.yaml
- azure-managed-cluster.yaml

patches:
- path: cluster-refs.yaml

sortOptions:
  order: fifo
