apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../base
- azure-cluster.yaml
- control-plane.yaml

patches:
- path: cluster-refs.yaml

sortOptions:
  order: fifo
