apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../../../kubeadmconfigtemplate/base/default

# patches:
#   - path: patches/worker.yaml
#     target:
#       kind: AzureASOMachineTemplate
#       name: \$\{CLUSTER_NAME\}

configurations:
  - configurations/name.yaml

replacements:
  - source:
      kind: KubeadmConfigTemplate
      name: ${CLUSTER_NAME}
    targets:
      - select:
          group: cluster.x-k8s.io
          version: v1beta1
          kind: MachineDeployment
          name: ${CLUSTER_NAME}
        fieldPaths:
          - spec.template.spec.bootstrap.configRef.name
        options:
          create: true
  - source:
      kind: KubeadmConfigTemplate
      name: ${CLUSTER_NAME}
      fieldPath: apiVersion
    targets:
      - select:
          group: cluster.x-k8s.io
          version: v1beta1
          kind: MachineDeployment
          name: ${CLUSTER_NAME}
        fieldPaths:
          - spec.template.spec.bootstrap.configRef.apiVersion
        options:
          create: true
  - source:
      kind: KubeadmConfigTemplate
      name: ${CLUSTER_NAME}
      fieldPath: kind
    targets:
      - select:
          group: cluster.x-k8s.io
          version: v1beta1
          kind: MachineDeployment
          name: ${CLUSTER_NAME}
        fieldPaths:
          - spec.template.spec.bootstrap.configRef.kind
        options:
          create: true
