# permissions for end users to edit asomanagedcontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: asomanagedcontrolplane-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: capaso
    app.kubernetes.io/part-of: capaso
    app.kubernetes.io/managed-by: kustomize
  name: asomanagedcontrolplane-editor-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - asomanagedcontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - asomanagedcontrolplanes/status
  verbs:
  - get
