# permissions for end users to view asomanagedmachinepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: asomanagedmachinepool-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: capaso
    app.kubernetes.io/part-of: capaso
    app.kubernetes.io/managed-by: kustomize
  name: asomanagedmachinepool-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - asomanagedmachinepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - asomanagedmachinepools/status
  verbs:
  - get
