apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -md-0

resources:
  - ../default

components:
  - ../../components/kubeadmconfigtemplate
  - ../../components/azureasomachinetemplate
