kind: Secret
apiVersion: v1
metadata:
  name: ${CLUSTER_NAME}-azure-json
stringData:
  controlplane: |
    {
      "tenantId": "${AZURE_TENANT_ID}",
      "subscriptionId": "${AZURE_SUBSCRIPTION_ID}",
      "resourceGroup": "${CLUSTER_NAME}",
      "location": "${AZURE_LOCATION}",
      "subnetName": "${CLUSTER_NAME}-controlplane",
      "vnetName": "${CLUSTER_NAME}",
      "vnetResourceGroup": "${CLUSTER_NAME}",
      "securityGroupName": "${CLUSTER_NAME}-worker",
      "securityGroupResourceGroup": "${CLUSTER_NAME}",
      "routeTableName": "${CLUSTER_NAME}",
      "loadBalancerSku": "standard",
      "useInstanceMetadata": true,
      "useManagedIdentityExtension": true
    }
  worker: |
    {
      "tenantId": "${AZURE_TENANT_ID}",
      "subscriptionId": "${AZURE_SUBSCRIPTION_ID}",
      "resourceGroup": "${CLUSTER_NAME}",
      "location": "${AZURE_LOCATION}",
      "subnetName": "${CLUSTER_NAME}-worker",
      "vnetName": "${CLUSTER_NAME}",
      "vnetResourceGroup": "${CLUSTER_NAME}",
      "securityGroupName": "${CLUSTER_NAME}-worker",
      "securityGroupResourceGroup": "${CLUSTER_NAME}",
      "routeTableName": "${CLUSTER_NAME}",
      "loadBalancerSku": "standard",
      "useInstanceMetadata": true,
      "useManagedIdentityExtension": true
    }
