# This contains a final representation of a full Cluster.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

components:
  - ../../components/azureasocluster/overlays/apiserver-port-6443
  - ../../components/kubeadmcontrolplane/overlays/azureasomachinetemplate
  - ../../components/machinedeployment/overlays/azureasomachinetemplate-kubeadmconfigtemplate
  - ../../components/machinedeployment/overlays/azureasomachinetemplate-kubeadmconfigtemplate-windows
  - ../../components/azureasocluster/components/ssh
  - ../../components/azureasomachinetemplate/components/ssh-linux

sortOptions:
  order: fifo
