apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patches/azureasomachinetemplate.yaml
    target:
      kind: AzureASOMachineTemplate
      name: \$\{CLUSTER_NAME\}
  - path: patches/secret.yaml
