apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -win

resources:
  - ../default

components:
  - ../../components/windows
  - ../../components/kubeadmconfigtemplate
  - ../../../kubeadmconfigtemplate/components/windows
  - ../../components/azureasomachinetemplate
  - ../../../azureasomachinetemplate/components/windows
