apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
spec:
  clusterNetwork:
    apiServerPort: 6443
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: AzureASOCluster
    name: ${CLUSTER_NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: AzureASOCluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
spec:
  resources:
  - apiVersion: resources.azure.com/v1api20200601
    kind: ResourceGroup
    metadata:
      annotations:
        serviceoperator.azure.com/credential-from: ${ASO_CREDENTIAL_SECRET_NAME}
      name: ${CLUSTER_NAME}
    spec:
      location: ${AZURE_LOCATION}
  - apiVersion: network.azure.com/v1api20240301
    kind: VirtualNetwork
    metadata:
      annotations:
        serviceoperator.azure.com/credential-from: ${ASO_CREDENTIAL_SECRET_NAME}
      name: ${CLUSTER_NAME}
    spec:
      addressSpace:
        addressPrefixes:
        - 10.0.0.0/16
      location: ${AZURE_LOCATION}
      owner:
        name: ${CLUSTER_NAME}
  - apiVersion: network.azure.com/v1api20240301
    kind: VirtualNetworksSubnet
    metadata:
      annotations:
        serviceoperator.azure.com/credential-from: ${ASO_CREDENTIAL_SECRET_NAME}
      name: ${CLUSTER_NAME}-controlplane
    spec:
      addressPrefix: 10.0.0.0/24
      natGateway:
        reference:
          group: network.azure.com
          kind: NatGateway
          name: ${CLUSTER_NAME}
      networkSecurityGroup:
        reference:
          group: network.azure.com
          kind: NetworkSecurityGroup
          name: ${CLUSTER_NAME}-controlplane
      owner:
        name: ${CLUSTER_NAME}
  - apiVersion: network.azure.com/v1api20240301
    kind: VirtualNetworksSubnet
    metadata:
      annotations:
        serviceoperator.azure.com/credential-from: ${ASO_CREDENTIAL_SECRET_NAME}
      name: ${CLUSTER_NAME}-worker
    spec:
      addressPrefix: 10.0.1.0/24
      natGateway:
        reference:
          group: network.azure.com
          kind: NatGateway
          name: ${CLUSTER_NAME}
      networkSecurityGroup:
        reference:
          group: network.azure.com
          kind: NetworkSecurityGroup
          name: ${CLUSTER_NAME}-worker
      owner:
        name: ${CLUSTER_NAME}
  - apiVersion: network.azure.com/v1api20240301
    kind: PublicIPAddress
    metadata:
      annotations:
        serviceoperator.azure.com/credential-from: ${ASO_CREDENTIAL_SECRET_NAME}
      name: ${CLUSTER_NAME}-controlplane
    spec:
      location: ${AZURE_LOCATION}
      owner:
        name: ${CLUSTER_NAME}
      publicIPAllocationMethod: Static
      sku:
        name: Standard
  - apiVersion: network.azure.com/v1api20240301
    kind: LoadBalancer
    metadata:
      annotations:
        serviceoperator.azure.com/credential-from: ${ASO_CREDENTIAL_SECRET_NAME}
      name: ${CLUSTER_NAME}
    spec:
      backendAddressPools:
      - name: controlplane
      frontendIPConfigurations:
      - name: controlplane
        publicIPAddress:
          reference:
            group: network.azure.com
            kind: PublicIPAddress
            name: ${CLUSTER_NAME}-controlplane
      loadBalancingRules:
      - backendAddressPools:
        - reference:
            armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${CLUSTER_NAME}/providers/Microsoft.Network/loadBalancers/${CLUSTER_NAME}/backendAddressPools/controlplane
        backendPort: 6443
        disableOutboundSnat: true
        frontendIPConfiguration:
          reference:
            armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${CLUSTER_NAME}/providers/Microsoft.Network/loadBalancers/${CLUSTER_NAME}/frontendIPConfigurations/controlplane
        frontendPort: 6443
        name: controlplane
        probe:
          reference:
            armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${CLUSTER_NAME}/providers/Microsoft.Network/loadBalancers/${CLUSTER_NAME}/probes/apiserver
        protocol: Tcp
      location: ${AZURE_LOCATION}
      owner:
        name: ${CLUSTER_NAME}
      probes:
      - name: apiserver
        port: 6443
        protocol: Https
        requestPath: /readyz
      sku:
        name: Standard
  - apiVersion: network.azure.com/v1api20240301
    kind: LoadBalancersInboundNatRule
    metadata:
      name: ${CLUSTER_NAME}
    spec:
      backendAddressPool:
        reference:
          armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${CLUSTER_NAME}/providers/Microsoft.Network/loadBalancers/${CLUSTER_NAME}/backendAddressPools/controlplane
      backendPort: 22
      frontendIPConfiguration:
        reference:
          armId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${CLUSTER_NAME}/providers/Microsoft.Network/loadBalancers/${CLUSTER_NAME}/frontendIPConfigurations/controlplane
      frontendPortRangeEnd: 2204
      frontendPortRangeStart: 2200
      owner:
        name: ${CLUSTER_NAME}
      protocol: Tcp
  - apiVersion: network.azure.com/v1api20240301
    kind: NetworkSecurityGroup
    metadata:
      annotations:
        serviceoperator.azure.com/credential-from: ${ASO_CREDENTIAL_SECRET_NAME}
      name: ${CLUSTER_NAME}-controlplane
    spec:
      location: ${AZURE_LOCATION}
      owner:
        name: ${CLUSTER_NAME}
  - apiVersion: network.azure.com/v1api20240301
    kind: NetworkSecurityGroupsSecurityRule
    metadata:
      annotations:
        serviceoperator.azure.com/credential-from: ${ASO_CREDENTIAL_SECRET_NAME}
      name: ${CLUSTER_NAME}-allow-apiserver
    spec:
      access: Allow
      azureName: AllowApiServer
      description: Allow access to kube-apiserver
      destinationAddressPrefix: '*'
      destinationPortRange: "6443"
      direction: Inbound
      owner:
        name: ${CLUSTER_NAME}-controlplane
      priority: 2000
      protocol: Tcp
      sourceAddressPrefix: '*'
      sourcePortRange: '*'
  - apiVersion: network.azure.com/v1api20240301
    kind: NetworkSecurityGroupsSecurityRule
    metadata:
      name: ${CLUSTER_NAME}-allow-ssh
    spec:
      access: Allow
      azureName: AllowSSH
      description: Allow SSH access
      destinationAddressPrefix: '*'
      destinationPortRange: "22"
      direction: Inbound
      owner:
        name: ${CLUSTER_NAME}-controlplane
      priority: 2200
      protocol: Tcp
      sourceAddressPrefix: '*'
      sourcePortRange: '*'
  - apiVersion: network.azure.com/v1api20240301
    kind: NetworkSecurityGroup
    metadata:
      annotations:
        serviceoperator.azure.com/credential-from: ${ASO_CREDENTIAL_SECRET_NAME}
      name: ${CLUSTER_NAME}-worker
    spec:
      location: ${AZURE_LOCATION}
      owner:
        name: ${CLUSTER_NAME}
  - apiVersion: network.azure.com/v1api20240301
    kind: PublicIPAddress
    metadata:
      name: ${CLUSTER_NAME}-nat-gateway
    spec:
      location: ${AZURE_LOCATION}
      publicIPAllocationMethod: Static
      sku:
        name: Standard
  - apiVersion: network.azure.com/v1api20240301
    kind: NatGateway
    metadata:
      annotations:
        serviceoperator.azure.com/credential-from: ${ASO_CREDENTIAL_SECRET_NAME}
      name: ${CLUSTER_NAME}
    spec:
      location: ${AZURE_LOCATION}
      owner:
        name: ${CLUSTER_NAME}
      publicIpAddresses:
      - reference:
          group: network.azure.com
          kind: PublicIPAddress
          name: ${CLUSTER_NAME}-nat-gateway
      sku:
        name: Standard
  - apiVersion: network.azure.com/v1api20240301
    kind: RouteTable
    metadata:
      name: ${CLUSTER_NAME}
    spec:
      location: ${AZURE_LOCATION}
      owner:
        name: ${CLUSTER_NAME}
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CLUSTER_NAME}-azure-json
  namespace: default
stringData:
  controlplane: |
    {
      "tenantId": "${AZURE_TENANT_ID}",
      "subscriptionId": "${AZURE_SUBSCRIPTION_ID}",
      "resourceGroup": "${CLUSTER_NAME}",
      "location": "${AZURE_LOCATION}",
      "subnetName": "${CLUSTER_NAME}-controlplane",
      "vnetName": "${CLUSTER_NAME}",
      "vnetResourceGroup": "${CLUSTER_NAME}",
      "securityGroupName": "${CLUSTER_NAME}-worker",
      "securityGroupResourceGroup": "${CLUSTER_NAME}",
      "routeTableName": "${CLUSTER_NAME}",
      "loadBalancerSku": "standard",
      "useInstanceMetadata": true,
      "useManagedIdentityExtension": true
    }
  worker: |
    {
      "tenantId": "${AZURE_TENANT_ID}",
      "subscriptionId": "${AZURE_SUBSCRIPTION_ID}",
      "resourceGroup": "${CLUSTER_NAME}",
      "location": "${AZURE_LOCATION}",
      "subnetName": "${CLUSTER_NAME}-worker",
      "vnetName": "${CLUSTER_NAME}",
      "vnetResourceGroup": "${CLUSTER_NAME}",
      "securityGroupName": "${CLUSTER_NAME}-worker",
      "securityGroupResourceGroup": "${CLUSTER_NAME}",
      "routeTableName": "${CLUSTER_NAME}",
      "loadBalancerSku": "standard",
      "useInstanceMetadata": true,
      "useManagedIdentityExtension": true
    }
