# This contains configuration for an AzureASOCluster exposing SSH.

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patches/resources.yaml
    target:
      kind: AzureASOCluster
      name: \$\{CLUSTER_NAME\}
