apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  kubeadmConfigSpec:
    postKubeadmCommands:
      # This frees up :53 on the host for the coredns pods
      - echo "DNSStubListener=no" >> /etc/systemd/resolved.conf
      - mv /etc/resolv.conf /etc/resolv.conf.OLD && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
      - systemctl restart systemd-resolved containerd
    initConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data["local_hostname"] }}'
        kubeletExtraArgs:
          cluster-dns: "fd00::10"
      localAPIEndpoint:
        advertiseAddress: "::"
        bindPort: 6443
    joinConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data["local_hostname"] }}'
        kubeletExtraArgs:
          cluster-dns: "fd00::10"
      controlPlane:
        localAPIEndpoint:
          advertiseAddress: "::"
          bindPort: 6443
    clusterConfiguration:
      apiServer:
        timeoutForControlPlane: 20m
        extraArgs:
          bind-address: "::"
      controllerManager:
        extraArgs:
          #required for ipv6 using calico
          allocate-node-cidrs: "true"
          cluster-cidr: "2001:1234:5678:9a40::/58"
          configure-cloud-routes: "true"
          bind-address: "::"
      scheduler:
        extraArgs:
          bind-address: "::"
